set(DEST_DIR ${SOURCES_ARG})
message(STATUS "DEST_DIR: ${DEST_DIR}")
file(GLOB COMPILE_COMMANDS "${DEST_DIR}/*.json")
file(WRITE ${DEST_DIR}/../compile_commands.json "[\n")
foreach(f ${COMPILE_COMMANDS})
  file(READ ${f} content)
  file(APPEND ${DEST_DIR}/../compile_commands.json "${content}")
endforeach(f ${COMPILE_COMMANDS})
file(APPEND ${DEST_DIR}/../compile_commands.json "]\n")
